# Generated by Django 4.0.6 on 2022-07-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat', '0004_alter_sponsor_phone_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
