# Generated by Django 4.0.6 on 2022-07-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat', '0005_alter_sponsor_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
