# Generated by Django 4.0.6 on 2022-07-27 04:25

from django.db import migrations, models
import metsenat.models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat', '0006_alter_sponsor_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount_pay',
            field=models.FloatField(validators=[metsenat.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='student',
            name='amount_contract',
            field=models.FloatField(validators=[metsenat.models.validate_amount]),
        ),
    ]
