# Generated by Django 4.0.6 on 2022-07-27 04:32

from django.db import migrations, models
import django.db.models.deletion
import metsenat.models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat', '0007_alter_sponsor_amount_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsenat.student', validators=[metsenat.models.validate_activ]),
        ),
    ]
