# Generated by Django 4.0.6 on 2022-07-27 04:50

from django.db import migrations, models
import metsenat.models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat', '0008_alter_studentsponsor_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='amount',
            field=models.FloatField(validators=[metsenat.models.validate_amount]),
        ),
    ]
