# Generated by Django 4.0.6 on 2022-08-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat', '0010_alter_studentsponsor_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='otm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metsenat.otm'),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsenat.sponsor'),
        ),
    ]
